# Generated by Django 5.2.8 on 2026-07-31 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_last_login_date_profile_login_streak_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginOTP',
        ),
    ]
