# Generated by Django 5.2.8 on 2026-07-31 18:53

import knowledgex.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_loginotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=knowledgex.storage.CloudinaryMediaStorage(), upload_to='profiles/'),
        ),
    ]
