# Generated by Django 5.2.8 on 2026-04-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_subject_branch_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='extracted_text_pages',
            field=models.JSONField(blank=True, default=dict, help_text='JSON mapping of page numbers to text content.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('COMMENT', 'Comment'), ('REPLY', 'Reply'), ('RATING', 'Rating'), ('REPORT', 'Report'), ('REPORT_STATUS', 'Report Status Update'), ('VERIFICATION', 'Verification Update')], max_length=20),
        ),
    ]
