# Generated by Django 5.2.8 on 2026-05-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_resource_extracted_text_pages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='Short form e.g. "OS", "DBMS", "CN", "DS"', max_length=20),
        ),
    ]
