# Generated by Django 5.2.8 on 2026-07-31 18:53

import django.core.validators
import knowledgex.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_subject_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(storage=knowledgex.storage.CloudinaryMediaStorage(), upload_to='uploads/resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'docx', 'zip', 'ppt', 'pptx'])]),
        ),
    ]
